apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: detector
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames: ["demo"]
  selector:
    matchLabels:
      app: detector
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      # If your API serves HTTPS inside the pod, uncomment:
      # scheme: https
      # tlsConfig:
      #   insecureSkipVerify: true
