apiVersion: v1
kind: Namespace
metadata:
  name: demo-shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-shop
  namespace: demo-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-shop
  template:
    metadata:
      labels:
        app: demo-shop
    spec:
      containers:
      - name: demo-shop
        image: demo-shop:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: API_BASE
          value: http://detector.demo:8001
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: demo-shop
  namespace: demo-shop
spec:
  selector:
    app: demo-shop
  ports:
  - port: 80
    targetPort: 3005
