"""create security_state table

Revision ID: fbf89aca26c7
Revises: df9e776bd3fe
Create Date: 2025-08-06 19:07:08.379957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf89aca26c7'
down_revision: Union[str, None] = 'df9e776bd3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_chain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_state_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_policy_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_policy_id'), ['policy_id'], unique=False)

    with op.batch_alter_table('security_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_state_id'))

    op.drop_table('security_state')
    # ### end Alembic commands ###
