apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: detector
        image: detector:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-metrics
          containerPort: 8001
