apiVersion: v1
kind: Service
metadata:
  name: detector
  namespace: demo
  labels:
    app: detector
spec:
  selector:
    app: detector
  ports:
  - name: http-metrics
    port: 8001
    targetPort: 8001
