#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
kind: Deployment
apiVersion: apps/v1
metadata:
  name: users
  labels:
    component: sockshop
spec:
  template:
    spec:
      containers:
        - name: users
          image: ghcr.io/helidon-sockshop/users-redis:2.2.0
