#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: payment
spec:
  cluster: SockShop
  role: Payment
  replicas: 1
  image: ghcr.io/helidon-sockshop/payment-coherence:2.2.0
  imagePullPolicy: Always
  env:
    - name: TRACING_HOST
      value: "jaeger-collector"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
  application:
    type: helidon
  jvm:
    memory:
      heapSize: 2g
  ports:
    - name: grpc
      port: 1408
      service:
        name: payment
    - name: http
      port: 7001
      service:
        name: payment-http
        port: 80
      serviceMonitor:
        enabled: true
